name: Kafka CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  kafka-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Start Kafka and Zookeeper Containers
      - name: Start Kafka and Zookeeper
        run: |
          mkdir -p kafka-docker
          echo "
          version: '3.8'
          services:
            zookeeper:
              image: confluentinc/cp-zookeeper:latest
              ports:
                - '2181:2181'
              environment:
                ZOOKEEPER_CLIENT_PORT: 2181
                ZOOKEEPER_TICK_TIME: 2000
          
            kafka:
              image: confluentinc/cp-kafka:latest
              ports:
                - '9092:9092'
              depends_on:
                - zookeeper
              environment:
                KAFKA_BROKER_ID: 1
                KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
                KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          " > kafka-docker/docker-compose.yml
          
          cd kafka-docker
          docker-compose up -d
          docker-compose ps

      # Step 4: Verify Kafka is Running
      - name: Verify Kafka Setup
        run: |
          docker ps
          echo "Waiting for Kafka to start..."
          sleep 20

      # Step 5: Produce and Consume Kafka Messages
      - name: Produce and Consume Messages
        run: |
          docker exec kafka-docker-kafka-1 kafka-topics --create --topic test-topic --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1
          echo "Hello, Kafka!" | docker exec -i kafka-docker-kafka-1 kafka-console-producer --topic test-topic --bootstrap-server localhost:9092
          docker exec kafka-docker-kafka-1 kafka-console-consumer --topic test-topic --bootstrap-server localhost:9092 --from-beginning --timeout-ms 20000